const fs = require('fs');
const path = require('path');

const localResourceDir = path.join(__dirname, '..', 'Resource', 'Judgements');
const outputFilePath = path.join(__dirname, '..', 'Resource', 'Judgements_Search_References_v57.md');

let cases = new Map();

function loadBatchedCases() {
    console.log("Scanning batched files...");
    const files = fs.readdirSync(localResourceDir);
    for (const file of files) {
        if (file.endsWith('.json') && file.startsWith('batch_')) {
            try {
                const data = JSON.parse(fs.readFileSync(path.join(localResourceDir, file), 'utf8'));
                if (Array.isArray(data)) {
                    for (const item of data) {
                        if (item.Id) cases.set(item.Id, item);
                    }
                }
            } catch (e) {
                console.error(`Error reading file ${file}:`, e.message);
            }
        }
    }
    console.log(`Loaded ${cases.size} unique cases from batches.`);
}

function run() {
    loadBatchedCases();

    // Group cases by theory
    let groupedCases = {};

    cases.forEach(c => {
        if (!c.theories) {
             c.theories = [c.theory]; // Fallback for older format
        }

        c.theories.forEach(theory => {
            if (!groupedCases[theory]) {
                groupedCases[theory] = [];
            }
            groupedCases[theory].push(c);
        });
    });

    let md = `# Judgements Search & Precedent Reference Library (v57)\n\n`;
    md += `This document contains structured research references generated by scanning the batched database of judgments under \`Resource/Judgements/\`.\n\n`;

    for (const theory in groupedCases) {
        md += `## Theory Group: ${theory}\n\n`;
        const theoryCases = groupedCases[theory];

        // Sort by length of judgment text (longer = potentially more detailed)
        theoryCases.sort((a, b) => {
            const lenA = a.full_judgment ? a.full_judgment.length : 0;
            const lenB = b.full_judgment ? b.full_judgment.length : 0;
            return lenB - lenA;
        });

        // Take top 15 for index
        theoryCases.slice(0, 15).forEach((c, idx) => {
            const cleanParties = (c.parties || 'N/A').replace(/\r/g, ' ').replace(/\n/g, ' ').trim();
            const cleanRef = (c.book_ref || 'N/A').trim();
            const cleanCase = (c.caseno || 'N/A').trim();
            const year = c.jud_year || 'N/A';
            const court = c.case_type_name || 'N/A';
            const bench = (c.justice_names && c.justice_names.length > 0) ? c.justice_names.join(', ') : 'N/A';

            // Extract a snippet (first 1000 chars of judgment)
            let snippet = "";
            if (c.full_judgment) {
                 snippet = c.full_judgment.substring(0, 1000).replace(/\r\n/g, ' ').replace(/\n/g, ' ') + (c.full_judgment.length > 1000 ? '...' : '');
            }

            md += `### [${idx + 1}] Precedent: ${cleanRef !== 'N/A' && cleanRef !== '' ? cleanRef : cleanCase}\n`;
            md += `- **Parties:** *${cleanParties}*\n`;
            md += `- **Court:** ${court} | **Bench:** ${bench}\n`;
            md += `- **Year:** ${year}\n`;
            md += `- **Theory Group:** ${theory}\n`;
            md += `- **Key Holding / Context Snippet:**\n`;
            md += `  > *"${snippet}"*\n\n`;
        });

        md += `---\n\n`;
    }

    fs.writeFileSync(outputFilePath, md, 'utf-8');
    console.log(`Successfully wrote reference library to: ${outputFilePath}`);
}

run();
