const fs = require('fs');
const path = require('path');

const judgementsDir = 'f:\\Mahfoz\\Advocacy\\Resource\\Judgements';
const outputFilePath = 'f:\\Mahfoz\\Advocacy\\Resource\\Judgements_Search_References.md';

const searchCategories = [
  {
    key: 'A_nawab_transition',
    title: 'A. Core — Nawab Estate to SA Transition',
    terms: [
      /dhaka\s+nawab/i, /nawab\s+estate/i, /court\s+of\s+wards/i, /chief\s+manager/i,
      /approval\s+of\s+chief\s+manager/i, /settlement\s+without\s+approval/i, /khas\s+mahal/i,
      /government\s+estates\s+manual/i, /ঢাকা\s+নবাব/i, /নবাব\s+এস্টেট/i, /কোর্ট\s+অব\s+ওয়ার্ডস/i,
      /চিফ\s+ম্যানেজার/i, /খাস\s+মহল/i
    ]
  },
  {
    key: 'B_sa_presumption',
    title: 'B. SA Presumption — Statutory Sword',
    terms: [
      /section\s+144a/i, /144-a/i, /presumption\s+of\s+correctness/i, /finally\s+published/i,
      /record\s+of\s+rights/i, /sa\s+khatian/i, /rs\s+khatian/i, /recent\s+record\s+prevails/i,
      /১৪৪এ/i, /১৪৪ক/i, /চূড়ান্তভাবে\s+প্রকাশিত/i, /রেকর্ড\s+অব\s+রাইটস/i, /এসএ\s+খতিয়ান/i
    ]
  },
  {
    key: 'C_mutation_volume',
    title: 'C. Mutation/Volume — Administrative Weakness',
    terms: [
      /mutation\s+has\s+no\s+presumptive/i, /volume\s+entry/i, /interpolation/i, /different\s+ink/i,
      /correction\s+without\s+decree/i, /section\s+143/i, /section\s+144/i, /মিউটেশন/i, /ভলিউম/i,
      /ভিন্ন\s+কালি/i, /সংশোধন/i, /ডিক্রি\s+ছাড়া/i
    ]
  },
  {
    key: 'D_partition_tech',
    title: 'D. Partition Technicalities',
    terms: [
      /partial\s+partition/i, /hotchpot/i, /non-joinder/i, /non\s+joinder/i, /order\s+1\s+rule\s+9/i,
      /cpc\s+order\s+xxiii\s+rule\s+3/i, /solenama/i, /compromise\s+decree/i, /আংশিক\s+বাটোয়ারা/i,
      /হচপট/i, /পক্ষদোষ/i, /সোলেনামা/i
    ]
  },
  {
    key: 'E_burden_of_proof',
    title: 'E. Burden of Proof — Section 103 Evidence Act',
    terms: [
      /section\s+103\s+evidence/i, /burden\s+shifts/i, /onus\s+to\s+prove\s+correction/i, /plaintiff\s+prima\s+facie/i,
      /১০৩\s+ধারা/i, /প্রমাণের\s+দায়িত্ব/i
    ]
  },
  {
    key: 'F_limitation_jurisdiction',
    title: 'F. Limitation & Munsif Jurisdiction',
    terms: [
      /misc\s+case/i, /miscellaneous\s+case/i, /record\s+correction/i, /limitation/i,
      /revenue\s+officer\s+not\s+court/i, /মিস\s+কেস/i, /খতিয়ান\s+সংশোধন/i, /তামাদি/i, /রাজস্ব\s+কর্মকর্তা/i
    ]
  }
];

const results = {};
searchCategories.forEach(cat => {
  results[cat.key] = [];
});

try {
  const files = fs.readdirSync(judgementsDir).filter(file => file.endsWith('.json'));
  console.log(`Scanning ${files.length} judgment files...`);

  files.forEach(filename => {
    const filepath = path.join(judgementsDir, filename);
    try {
      const content = fs.readFileSync(filepath, 'utf-8');
      const data = JSON.parse(content);

      const fullJud = data.full_judgment || "";
      const bookRef = data.book_ref || "";
      const caseno = data.caseno || "";
      const parties = data.parties || "";
      const scrapedKw = data._scraped_keyword || "";

      const contentToSearch = `${bookRef} ${caseno} ${parties} ${fullJud} ${scrapedKw}`;

      searchCategories.forEach(cat => {
        const matched = [];
        cat.terms.forEach(term => {
          if (term.test(contentToSearch)) {
            matched.push(term.toString());
          }
        });

        if (matched.length > 0) {
          // Find context paragraph
          const paras = fullJud.split('\n');
          let snippet = '';
          for (const p of paras) {
            for (const term of cat.terms) {
              if (term.test(p)) {
                snippet = p.trim();
                break;
              }
            }
            if (snippet) break;
          }
          if (!snippet && paras.length > 0) {
            snippet = paras[0].trim();
          }

          results[cat.key].push({
            file: filename,
            book_ref: bookRef || 'N/A',
            caseno: caseno || 'N/A',
            parties: parties || 'N/A',
            match_count: matched.length,
            matched_terms: matched,
            full_text_len: fullJud.length,
            snippet: snippet,
            full_judgment: fullJud
          });
        }
      });
    } catch (err) {
      // ignore
    }
  });

  // Compile Markdown report
  let md = `# Judgements Search & Precedent Reference Library\n\n`;
  md += `This document contains structured research references generated by scanning the database of 1,000+ judgments under \`Resource/Judgements/\` using the specified Keyword Bank. These references directly support the appeal arguments for **আপীল মামলা নং ৩৮/২০২৬, টাঙ্গাইল**.\n\n`;
  md += `## Directory Summary\n- **Database Location:** \`Resource/Judgements/\`\n- **Total Scanned Files:** ${files.length}\n- **Date of Search:** ${new Date().toISOString().split('T')[0]}\n\n`;

  searchCategories.forEach(cat => {
    md += `## ${cat.title}\n\n`;
    const matches = results[cat.key];
    
    // Sort: most unique matches first, then longest judgment (to find deep analyses)
    matches.sort((a, b) => {
      if (b.match_count !== a.match_count) {
        return b.match_count - a.match_count;
      }
      return b.full_text_len - a.full_text_len;
    });

    md += `Found **${matches.length}** matches in this category. Showing top verified precedents below:\n\n`;

    matches.slice(0, 12).forEach((m, idx) => {
      const cleanParties = m.parties.replace(/\r/g, ' ').replace(/\n/g, ' ').trim();
      const cleanRef = m.book_ref.trim();
      const cleanCase = m.caseno.trim();
      const relativePath = `file:///f:/Mahfoz/Advocacy/Resource/Judgements/${m.file}`;
      
      md += `### [${idx + 1}] Precedent: ${cleanRef !== 'N/A' ? cleanRef : cleanCase}\n`;
      md += `- **File:** [${m.file}](${relativePath})\n`;
      md += `- **Case Info:** ${cleanCase} | **Parties:** *${cleanParties}*\n`;
      md += `- **Relevance Score:** ${m.match_count} matched terms: \`${m.matched_terms.join(', ')}\`\n`;
      md += `- **Key Holding / Context:**\n`;
      md += `  > *"${m.snippet.substring(0, 1000)}${m.snippet.length > 1000 ? '...' : ''}"*\n\n`;
    });

    md += `---\n\n`;
  });

  fs.writeFileSync(outputFilePath, md, 'utf-8');
  console.log(`Successfully wrote references library to: ${outputFilePath}`);

} catch (err) {
  console.error(`Fatal search error: ${err.message}`);
}
